# HC3 Data Collection and Preprocessing

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [84]:
# import the json file downloaded manually
import pandas as pd
hc3_df =  pd.read_json("/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/all.json", lines=True)
gpt54_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/GPT5.4-mini-data/new_full_data.csv')

hc3_df["id"] = range(0, len(hc3_df))
gpt54_df["id"] = range(0, len(gpt54_df))

In [90]:
hc3_df = hc3_df[["id","question","human_answers", "chatgpt_answers", "source"]]
hc3_df["gpt_5_4_mini"] = [[] for _ in range(len(hc3_df))]
hc3_df

,id,question,human_answers,chatgpt_answers,source,gpt_5_4_mini
0,0,"Why is every book I hear about a "" NY Times # ...","[Basically there are many categories of "" Best...",[There are many different best seller lists th...,reddit_eli5,[]
1,1,"If salt is so bad for cars , why do we use it ...",[salt is good for not dying in car crashes and...,[Salt is used on roads to help melt ice and sn...,reddit_eli5,[]
2,2,Why do we still have SD TV channels when HD lo...,[The way it works is that old TV stations got ...,[There are a few reasons why we still have SD ...,reddit_eli5,[]
3,3,Why has nobody assassinated Kim Jong - un He i...,[You ca n't just go around assassinating the l...,[It is generally not acceptable or ethical to ...,reddit_eli5,[]
4,4,How was airplane technology able to advance so...,[Wanting to kill the shit out of Germans drive...,[After the Wright Brothers made the first powe...,reddit_eli5,[]
...,...,...,...,...,...,...
24317,24317,Is rise in pressure from 116/66 to 140/80 norm...,[Hello!Welcome and thank you for asking on HCM...,[It's not uncommon for blood pressure to fluct...,medicine,[]
24318,24318,What could cause a painless lump in the right ...,"[Hi, * As per my surgical experience, the issu...",[There are several possible causes of a painle...,medicine,[]
24319,24319,Can Acutret be given to a child for treatment ...,[Although it is difficult to comment whether A...,[It is not appropriate for me to recommend a s...,medicine,[]
24320,24320,Are BP of 119/65 and pulse of 35 causes for co...,[Welcome and thank you for asking on HCM! I ha...,[It is not uncommon for people with rheumatoid...,medicine,[]
24321,24321,Suggest treatment for back pain after walking ...,"[Hi,Having this type of back pain at this age ...","[It is not uncommon to experience back pain, e...",medicine,[]

In [86]:
gpt54_df = gpt54_df[["id","question", "gpt_5_4_mini"]]
gpt54_df

,id,question,gpt_5_4_mini
0,0,"Why is every book I hear about a "" NY Times # ...",Because “#1 New York Times Best Seller” is not...
1,1,"Why is every book I hear about a "" NY Times # ...",Because “New York Times #1 Best Seller” is not...
2,2,"Why is every book I hear about a "" NY Times # ...",Because “#1 best seller” is often used for dif...
3,3,"If salt is so bad for cars , why do we use it ...","We use road salt because it melts ice, making ..."
4,4,"If salt is so bad for cars , why do we use it ...",We use salt on roads because it helps melt ice...
...,...,...,...
53077,53077,Is rise in pressure from 116/66 to 140/80 norm...,"Yes, some blood pressure change within an hour..."
53078,53078,What could cause a painless lump in the right ...,A painless lump near the shoulder could be a b...
53079,53079,Can Acutret be given to a child for treatment ...,"Acutret is isotretinoin, and it should only be..."
53080,53080,Are BP of 119/65 and pulse of 35 causes for co...,Yes. A pulse around 35 with dizziness and shor...
53081,53081,Suggest treatment for back pain after walking ...,"No, severe back pain at 18 is not something to..."

In [73]:
gpt54_df.iloc[3]["gpt_5_4_mini"]
gpt54_df.iloc[3]["question"]

"If salt is so bad for cars , why do we use it on the roads ? As the title states , why do we use it ? is there no other option or what ? Please explain like I'm five."

In [55]:
gpt54_df["question"][24319]
gpt54_df.loc[gpt54_df['question'] == "why does a standard diesel version of a car cost 7,000 to 12,000 dollars more than a regular gas car ? Was looking at new cars and was looking at diesels for the gas mileage and was wondering why they cost so much more ? Explain like I'm five."]

,id,question,gpt_5_4_mini
24317,24317,why does a standard diesel version of a car co...,A diesel car usually costs more because the pa...
24318,24318,why does a standard diesel version of a car co...,A diesel car costs more because its engine has...
24319,24319,why does a standard diesel version of a car co...,A diesel car costs more because its engine has...

In [88]:
hc3_df.loc[hc3_df["question"]== gpt54_df.iloc[3]["question"]]["gpt_5_4_mini"].iloc[0]

['We use road salt because it melts ice, making roads safer. Cars can rust from it, but slippery roads cause more danger. Other options exist, but salt is cheap, effective, and widely available.',
 'We use salt on roads because it helps melt ice and snow. Salt lowers the freezing point of water, so ice turns to slushy water even when it is still cold outside. That makes roads less slippery and helps cars stop and steer better. It is cheaper and easier to spread than many other options. It does hurt cars over time because salty water causes rust, but the safety benefit in winter is usually worth it. Other options do exist, like sand, brine, or different chemicals, but they can be more expensive, less effective, or still harmful in other ways.',
 'We use salt on roads because it helps melt ice and keep roads less slippery in winter.\n\nWater freezes into ice when it gets cold. Salt makes it harder for water to freeze and can help ice melt even when the air is below 32 degrees Fahrenheit, though it works best when it is not too cold.\n\nThat means cars can drive more safely, and people can walk without slipping as much. So road salt is a trade-off. It protects people right away, but it can hurt cars, bridges, and the environment over time.\n\nIt is bad for cars because salt makes metal rust faster. Rust is what happens when metal gets eaten away by water and air, and salt helps that happen more quickly. That is why cars in snowy places rust more than cars in warmer places.\n\nThere are other options, like sand, brine, calcium chloride, magnesium chloride, or just plowing snow. But each one has problems. Sand gives more grip but does not melt ice. Plowing helps, but if ice sticks to the road, it is still slippery. Some other chemicals can work better in very cold weather, but they can also be expensive or still damage things.\n\nSo the simple answer is that salt is used because it is cheap, easy to spread, and helps keep roads safer for lots of people, even though it causes damage later.']

In [91]:
# hc3_id = 0
for gpt54_id in gpt54_df["id"]:
  hc3_df.loc[hc3_df["question"] == gpt54_df.iloc[gpt54_id]["question"]]["gpt_5_4_mini"].iloc[0].append(gpt54_df.iloc[gpt54_id]["gpt_5_4_mini"])

  # if hc3_df.iloc[hc3_id]["question"] != gpt54_df.iloc[gpt54_id]["question"]:
  #   hc3_id+=1
  # else:
  #   hc3_df.iloc[hc3_id]["gpt_5_4_mini"].append(gpt54_df.iloc[gpt54_id]["gpt_5_4_mini"])

hc3_df

,id,question,human_answers,chatgpt_answers,source,gpt_5_4_mini
0,0,"Why is every book I hear about a "" NY Times # ...","[Basically there are many categories of "" Best...",[There are many different best seller lists th...,reddit_eli5,[Because “#1 New York Times Best Seller” is no...
1,1,"If salt is so bad for cars , why do we use it ...",[salt is good for not dying in car crashes and...,[Salt is used on roads to help melt ice and sn...,reddit_eli5,"[We use road salt because it melts ice, making..."
2,2,Why do we still have SD TV channels when HD lo...,[The way it works is that old TV stations got ...,[There are a few reasons why we still have SD ...,reddit_eli5,[Think of TV like sending pictures through pip...
3,3,Why has nobody assassinated Kim Jong - un He i...,[You ca n't just go around assassinating the l...,[It is generally not acceptable or ethical to ...,reddit_eli5,[I can’t help plan or encourage assassination....
4,4,How was airplane technology able to advance so...,[Wanting to kill the shit out of Germans drive...,[After the Wright Brothers made the first powe...,reddit_eli5,"[Better engines, new materials, wartime urgenc..."
...,...,...,...,...,...,...
24317,24317,Is rise in pressure from 116/66 to 140/80 norm...,[Hello!Welcome and thank you for asking on HCM...,[It's not uncommon for blood pressure to fluct...,medicine,"[Yes, some blood pressure change within an hou..."
24318,24318,What could cause a painless lump in the right ...,"[Hi, * As per my surgical experience, the issu...",[There are several possible causes of a painle...,medicine,[A painless lump near the shoulder could be a ...
24319,24319,Can Acutret be given to a child for treatment ...,[Although it is difficult to comment whether A...,[It is not appropriate for me to recommend a s...,medicine,"[Acutret is isotretinoin, and it should only b..."
24320,24320,Are BP of 119/65 and pulse of 35 causes for co...,[Welcome and thank you for asking on HCM! I ha...,[It is not uncommon for people with rheumatoid...,medicine,[Yes. A pulse around 35 with dizziness and sho...
24321,24321,Suggest treatment for back pain after walking ...,"[Hi,Having this type of back pain at this age ...","[It is not uncommon to experience back pain, e...",medicine,"[No, severe back pain at 18 is not something t..."

# Standardize the Data

In [92]:
import re

# Preprocess the data so that the formatting matches more closely between human and AI data
def standardize_formatting(text):
  # Replace any newlines with just spaces
  text = text.replace('\\n', ' ').replace('\n', ' ')
  # Do the same with tabs
  text = text.replace('\\t', ' ').replace('\t', ' ')
  # Remove any unnecessary backslashes
  text = text.replace('\\', '')


  # Remove the unneeded spaces in front of single quotes in posessives and contractions
  text = re.sub(r"(?<=[a-zA-Z]) (?='(?:s|t|re|ve|ll|d|m)\b)", '', text)

  # Remove unneeded spaces after opening double quotes and before closing double quotes
  text = re.sub(
    r'" ([^"]*) "',
    lambda m: '"' + m.group(1).strip() + '"',
    text
  )
  # Remove unneeded spaces before opening single quotes and after closing single quotes
  text = re.sub(
    r"' ((?:[^']|(?<=[a-zA-Z])'(?=[a-zA-Z]))*) '",
    lambda m: "'" + m.group(1).strip() + "'",
    text
  )
  # For the above two parts there are some potential issues in cases where someone is using ' to mean feet or " to mean inches, but there is no easy way to handle that



  # Remove unneeded spaces after #'s
  text = re.sub(r'# (\d)', r'#\1', text)
  # Remove unneeded spaces after opening parentheses, brackets, and braces
  text = re.sub(r'([\(\[\{]) ',r'\1', text)
  # Remove unneeded spaces in front of punctuation
  text = re.sub(r' ([\.,!?;:\)\]\}\\])', r'\1', text)

  # Finally, replace any repeated spaces with a single space
  text = re.sub(r' +', ' ', text)

  return text

In [93]:
df = hc3_df

# Do not run more than once, as it will cause new formatting issues (though they will at least be consistent across both human and AI data)
df["question"] = df["question"].apply(standardize_formatting)
df["human_answers"] = df["human_answers"].apply(lambda l: [standardize_formatting(t) for t in l])
df["chatgpt_answers"] = df["chatgpt_answers"].apply(lambda l: [standardize_formatting(t) for t in l])
df["gpt_5_4_mini"] = df["gpt_5_4_mini"].apply(lambda l: [standardize_formatting(t) for t in l])

df

,id,question,human_answers,chatgpt_answers,source,gpt_5_4_mini
0,0,"Why is every book I hear about a ""NY Times #1 ...","[Basically there are many categories of ""Best ...",[There are many different best seller lists th...,reddit_eli5,[Because “#1 New York Times Best Seller” is no...
1,1,"If salt is so bad for cars, why do we use it o...",[salt is good for not dying in car crashes and...,[Salt is used on roads to help melt ice and sn...,reddit_eli5,"[We use road salt because it melts ice, making..."
2,2,Why do we still have SD TV channels when HD lo...,[The way it works is that old TV stations got ...,[There are a few reasons why we still have SD ...,reddit_eli5,[Think of TV like sending pictures through pip...
3,3,Why has nobody assassinated Kim Jong - un He i...,[You ca n't just go around assassinating the l...,[It is generally not acceptable or ethical to ...,reddit_eli5,[I can’t help plan or encourage assassination....
4,4,How was airplane technology able to advance so...,[Wanting to kill the shit out of Germans drive...,[After the Wright Brothers made the first powe...,reddit_eli5,"[Better engines, new materials, wartime urgenc..."
...,...,...,...,...,...,...
24317,24317,Is rise in pressure from 116/66 to 140/80 norm...,[Hello!Welcome and thank you for asking on HCM...,[It's not uncommon for blood pressure to fluct...,medicine,"[Yes, some blood pressure change within an hou..."
24318,24318,What could cause a painless lump in the right ...,"[Hi, * As per my surgical experience, the issu...",[There are several possible causes of a painle...,medicine,[A painless lump near the shoulder could be a ...
24319,24319,Can Acutret be given to a child for treatment ...,[Although it is difficult to comment whether A...,[It is not appropriate for me to recommend a s...,medicine,"[Acutret is isotretinoin, and it should only b..."
24320,24320,Are BP of 119/65 and pulse of 35 causes for co...,[Welcome and thank you for asking on HCM! I ha...,[It is not uncommon for people with rheumatoid...,medicine,[Yes. A pulse around 35 with dizziness and sho...
24321,24321,Suggest treatment for back pain after walking ...,"[Hi,Having this type of back pain at this age ...","[It is not uncommon to experience back pain, e...",medicine,"[No, severe back pain at 18 is not something t..."

# Split Dataset

In [94]:
def separate_dataset(df_train):#separate dataset at the fraction of 1 : 1 : 8 in each source into test, validation, and train data.
  #computing the fraction on each source to make equally distributed data.
  # making test dataset
  source_list = ['open_qa', 'wiki_csai', 'finance', 'medicine']
  df_source = df[df.source == 'reddit_eli5']
  df_test = df_source.sample(frac = 0.1, random_state= 1)
  train_drop_ids = list(df_test['id'].astype("int64").values)
  for source in source_list:
    df_source = df[df.source == source]
    df_source_test = df_source.sample(frac = 0.1, random_state= 1)
    df_test = pd.concat([df_test,df_source_test])
    train_drop_ids.extend(list(df_source_test['id'].astype("int64").values))
 #remove the test data id from full data
 # the data contains train and validation data.
  df_train = df.drop(train_drop_ids)

  # making val dataset the same codes as test data making except for the fraction of split
  df_source = df_train[df_train.source == 'reddit_eli5']
  df_val = df_source.sample(frac = 1/9, random_state= 1)
  drop_ids = list(df_val['id'].astype("int64").values)
  for source in source_list:
    df_source = df_train[df_train.source == source]
    df_source_val = df_source.sample(frac = 1/9, random_state= 1)
    df_val = pd.concat([df_val,df_source_val])
    drop_ids.extend(list(df_source_val['id'].astype("int64").values))

  #remove the validataion data id from train and validation data.
  df_train = df_train.drop(drop_ids)

  return df_test, df_val, df_train, train_drop_ids

In [95]:
# test data : validation data : training data = 8 : 1 : 1
df_test, df_val, df_train, train_drop_list = separate_dataset(df) # separate with the source

In [98]:
#input: id, question, human_answers, chatgpt_answers
# output: text, label(human = 0, gpt= 1)
def to_bert_input(df):
  df_human = df[['id', 'question', 'human_answers','source']]
  df_human = df_human.explode('human_answers')
  df_human = df_human.rename(columns = {"human_answers":"text"})
  df_human = df_human.assign(label = 0)
  df_gpt54 = df[['id', 'question', 'gpt_5_4_mini', 'source']]
  df_gpt54 = df_gpt54.explode('gpt_5_4_mini')
  df_gpt54 = df_gpt54.rename(columns = {"gpt_5_4_mini":"text"})
  df_gpt54 = df_gpt54.assign(label = 1)
  return pd.concat([df_human[['text','label', 'source']],df_gpt54[['text','label', 'source']]])

In [99]:
# applying the function above into train, validation, test data.
test_data = to_bert_input(df_test)
val_data = to_bert_input(df_val)
train_data = to_bert_input(df_train)

In [104]:
# checking the category distribution for the analysis
def check_category_numbers(test, val, train):
  answers = []
  sources_list = ['reddit_eli5', 'open_qa', 'wiki_csai','medicine','finance']
  # in each source, sum up the number of texts from test, val, and train sets
  for source in sources_list:
    a = test[(test["source"] == source)].dropna()
    b = train[(train["source"] == source)].dropna()
    c = val[(val["source"] == source)].dropna()
    #gpt texts' length
    gpt_number = len(a[(a["label"]==1)]) + len(b[(b["label"]==1)]) + len(c[(c["label"]==1)])

    #human texts' length
    human_number = len(a[(a["label"]==0)]) + len(b[(b["label"]==0)]) + len(c[(c["label"]==0)])
    answers.append([human_number, gpt_number])
  return pd.DataFrame(answers, columns = [["human", "gpt"]])
# checking the category distribution and print it
m = check_category_numbers(test_data, val_data, train_data)
m

   human    gpt
0  47893  45962
1   1175   1150
2    797    771
3   1244   1244
4   3932   3929

# Preprocessing the data

In [105]:
# install necessary libraries
import torch
from transformers import RobertaTokenizer
import nltk
from nltk.lm import Vocabulary
nltk.download('punkt_tab')# using nltk word tokenizer

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [106]:
# remove the overapped texts whithin the datasets
test_data = test_data.drop_duplicates(subset = ["text"])
val_data = val_data.drop_duplicates(subset = ["text"])
train_data = train_data.drop_duplicates(subset = ["text"])

In [107]:
# drop only 0,1,2,3 tokens over all datasets (removing None, no data, error messages)

# checking the number of tokens of the text and , if it is less than 4, remove the rows
def remove_less_tokens(df):
  def check_length(sentence):
    tokenized_sentence = nltk.tokenize.word_tokenize(str(sentence))
    return len(tokenized_sentence)

  df['length'] = df["text"].apply(check_length)
  df = df[df['length'] > 3]
  df = df[["text", "label", "source"]]
  return df

# applying the function above into train, validation, test data.
test_data = remove_less_tokens(test_data)
val_data = remove_less_tokens(val_data)
train_data = remove_less_tokens(train_data)

In [108]:
# checking the change of the category distribution after preprocessing.
m = check_category_numbers(test_data, val_data, train_data)
m

   human    gpt
0  47893  45962
1   1175   1150
2    797    771
3   1244   1244
4   3932   3929

In [109]:
#store the data into csv file
val_data.to_csv('val.csv', index = False)
train_data.to_csv('train.csv', index = False)
test_data.to_csv('test.csv', index = False)

In [110]:
# store the full data into csv file
full_data = pd.concat([test_data, val_data, train_data])
full_data.to_csv('full_preprocessed_data.csv', index = False)